### ISSUE TITLE
PDF Parsing

### ISSUE THREAD

**Issue by victorbjorsvik** [victorbjorsvik/workproject_matching_algo#1]
We are having trouble parsing some of the PDFs - are able to get most of the skills, but we are not picking up Tim and Lucas' education

**Comment by LucaOezt** [comment]
is the space for Tim and my education just actually empty or wrong? just for my interest?

**Comment by victorbjorsvik** [comment]
> is the space for Tim and my education just actually empty or wrong? just for my interest?

We tried strip newlines and . but the inbuilt pandas methods didn't seem to work. Could try something like regular expressions or more thourough cleaning, but seeing as all the skills are being picked up I'd say this is not an issue at all. Also changed the PDF parser to one that is much faster. Marking this issue as solved
